accelerate launch train_maskmodel.py --output_dir "train_maskmodel/example" \
--logging_dir "logs" \
--num_train_epochs 5 \
--resolution 1024 \
--dataset_name "img1024" \
--image_column "image" \
--validation_image "examples/rssr/aid_stadium_202_4.jpg" \
--num_validation_images 1 \
--train_batch_size 16 \
--validation_steps 100 \
--first_stage_model_config "config/hat_mask.yaml" \
--dataloader_num_workers 8
