accelerate launch train_controlnext_sdxl_base.py --pretrained_model_name_or_path "checkpoint/stable-diffusion-xl-base-1.0" \
--pretrained_vae_model_name_or_path "checkpoint/sdxl-vae-fp16-fix" \
--variant fp16 \
--use_safetensors \
--output_dir "train_sdxl_base/example" \
--logging_dir "logs" \
--num_train_epochs 5 \
--resolution 1024 \
--gradient_checkpointing \
--set_grads_to_none \
--proportion_empty_prompts 0.2 \
--controlnet_scale_factor 1.0 \
--mixed_precision fp16 \
--enable_xformers_memory_efficient_attention \
--dataset_name "image1024_tar" \
--image_column jpg \
--caption_column txt \
--validation_prompt "satellite image." \
--validation_image "examples/rssr/LoveDa_Test_5382_lr.png"  \
--num_validation_images 4 \
--train_batch_size 2 \
--validation_steps 10 \
--first_stage_model_config "config/hat_mask.yaml" \
--cache_dir cache \
