#参照
model:
  hat:
    target: models.hat.HAT
    params:
      upscale: 4
      in_chans: 3
      img_size: 64
      window_size: 16
      compress_ratio: 3
      squeeze_factor: 30
      conv_scale: 0.01
      overlap_ratio: 0.5
      img_range: 1.
      depths: [ 6, 6, 6, 6, 6, 6 ]
      embed_dim: 180
      num_heads: [ 6, 6, 6, 6, 6, 6 ]
      mlp_ratio: 2
      upsampler: 'pixelshuffle'
      resi_connection: '1conv'
  unetresnet50:
    target: models.unetresnet50.UNetResNet50
    params:
      in_channels: 3
      out_channels: 1

train:
  hat_path: "checkpoint/hat/hatmse400000.pth"
  unetresnet50_path: "checkpoint/maskmodel/diffmodel.pth"